### PR TITLE
Update to 2.9.0post0

### PR DESCRIPTION
**Pull request by kynan**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by kynan** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
@kynan, 99.99% of the time, if upstream used pep440 correctly, post releases are meant to fix problems with packaging, usually the wheel. That means we can skip them. With that said, do you know if this is en exception and wrongly brings new code that would require us to make a new package?

**Comment by pganssle** [comment]
The `post0` release fixed something like a packaging issue with versions <3.6. Newer versions of `setuptools_scm` was generating a `_version.py` file that had embedded type hints, and so the wheel and sdists had code that didn't work in older versions. If you don't support versions older than 3.6, or if you build from source in a way that generates the `_version.py` with `setuptools < 8` on those platforms, you don't have to worry about `post0`.

**Comment by ocefpaf** [comment]
> If you don't support versions older than 3.6

We don't. So I guess we are good skipping this one.

PS: I went into auto-mode and did not even check the lib and who the autor is. Of course @pganssle would do the right thing with post releases. Thank Paul!

**Comment by kynan** [comment]
Thanks for clarifying! Confusingly, the [anaconda channel](https://anaconda.org/anaconda/python-dateutil) opted for packaging 2.9.0.post0 and not use `noarch`.

**Comment by ocefpaf** [comment]
> Thanks for clarifying! Confusingly, the [anaconda channel](https://anaconda.org/anaconda/python-dateutil) opted for packaging 2.9.0.post0 and not use `noarch`.

We do that to save resources, both human and computational. I guess anaconda has both to spare ;-p

**Comment by djhoese** [comment]
I don't know if this is a git tag issue or what, but according to the message I see on the bottom of this PR: https://github.com/dateutil/dateutil/pull/1285, it was only included in the `.post0` release of the package. Could we reopen this?

**Comment by djhoese** [comment]
Sorry, it looks like it is in 2.9.0: https://github.com/dateutil/dateutil/commit/f2293200747fb03d56c6c5997bfebeabe703576f

Edit: Looks like some recent package install I did downgraded dateutil in my environment.

**Pull request closed without merging**
